version: "3.1"

services:
  flowise:
    image: flowiseai/flowise
    container_name: flowise
    restart: unless-stopped
    environment:
      - PORT=3002
      - DATABASE_PATH=/root/.flowise
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - LOG_PATH=/root/.flowise/logs
      - DEBUG=True
      - LOG_LEVEL=debug
    ports:
      - "3002:3002"
    volumes:
      - ./data/flowise:/root/.flowise
      - ./data/flowise/output:/data/output
    command: /bin/sh -c "sleep 3; flowise start"
    # networks:
    #   network:
    #     ipv4_address: 10.5.0.3
  langfuse-server:
    image: ghcr.io/langfuse/langfuse:latest
    restart: unless-stopped
    depends_on:
      - flowise
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@tinybot.syncopated.net:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - NEXT_PUBLIC_SIGN_UP_DISABLED=${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
