#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__))

# TMPFS = File.join("/tmp/knowlecule")


# require "tty-which"

# unless TTY::Which.exist?("gum")
#   puts "Gum is not installed"
# end

require "knowlecule/ui"
