#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__))

# 
# require "tty-which"
#
# $gum = TTY::Which.which("guma")
#
# logger.fatal("gum not installed, exiting");exit if $gum.nil?

require "knowlecule"
